spring.application.name=NexusHR

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/nexushr
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA CONFIGURATION
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# SERVER PORT
# ===============================

server.port=8081

# ===============================
# JWT CONFIGURATION
# ===============================

jwt.secret=NexusHRSuperSecretKey2024ProductionGradeJWTKey!@#$%
jwt.expiration=86400000

# ===============================
# LOGGING
# ===============================

logging.level.com.nexushr=INFO
logging.level.org.springframework.security=WARN